### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by iKrishneel** [iKrishneel/igniter#1]
- [x] remove the hardcoded `train` and `val` in dataloaders
- [ ] build dataloaders separately for each keywords
- [x] move all engines to engine directory
- [x] enable writing checkpoints to path rather than overriding existing
- [ ] add function to zip and also upload the logs to s3 after every n epochs
- [x] #3
- [x] add transforms add argument to dataset
- [ ] #12
- [x] enable merging of configs
- [ ] append date folder inside the saving folder 
- [ ] fix the absolute path when `_base_` is given
- [ ] fix the gpu usage logging for distributed training
- [x] allow changing of progress bar, remove fixed tqdm one and make it configurable. 
- [x] make cli to train 
- [ ] fix the cli for distributed training
